export const FETCH_FOLDER = 'FETCH_FOLDER'
export const FETCHING_FOLDER = 'FETCHING_FOLDER'
export const FETCHING_FOLDER_SUCCESS = 'FETCHING_FOLDER_SUCCESS'
export const FETCHING_FOLDER_FAILED = 'FETCHING_FOLDER_FAILED'